# https://projecteuler.net/problem=2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

fibonacci_under <- function(n){
  x <- c(1, 1)
  while(x[length(x)] < n){
    x <- c(x, x[length(x) - 1] + x[length(x)])
  }
  x
}
x <- fibonacci_under(4e6)
x <- x[x %% 2 == 0]
sum(x)