### these are 27 verified correct solutions on Project Euler

library(dplyr)
library(stringr)

#1 -- VERIFIED CORRECT
# If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. 
# The sum of these multiples is 23.
# Find the sum of all the multiples of 3 or 5 below 1000.

multiples_below <- function(x, n){
  lapply(n, function(i){which(1:x %% i == 0)}) %>% unlist %>% unique
}

sum(multiples_below(999, c(3, 5)))



#2 -- VERIFIED CORRECT
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

fibonacci_under <- function(n){
  x <- c(1, 1)
  while(x[length(x)] < n){
    x <- c(x, x[length(x) - 1] + x[length(x)])
  }
  x
}
x <- fibonacci_under(4e6)
x <- x[x %% 2 == 0]
sum(x)



#3 -- VERIFIED CORRECT
# The prime factors of 13195 are 5, 7, 13 and 29.
# What is the largest prime factor of the number 600851475143?
my_factors <- pracma::factors(600851475143)
are_factors <- my_factors[as.logical(pracma::isprime(my_factors))]
max(are_factors)



